apiVersion: v1
kind: Service
metadata:
  name: images
  labels:
    app: images
spec:
  type: NodePort
  ports:
  - name: server
    port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: images
