apiVersion: v1
kind: Service
metadata:
  name: image
  labels:
    app: image
spec:
  type: NodePort
  ports:
  - name: server
    port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: image
